### ISSUE TITLE
I am getting this error!!

### ISSUE THREAD

**Issue by knsakib** [mziwisky/esp8266-dev#7]
unexpected tIDENTIFIER, expecting keyword_end
....vm.provision :shell, path: "vm-bootstrap.sh",privileged: fa...
...                               ^
/Users/khalidsakib/Documents/neox/esp8266.dev.box/Vagrantfile:21: syntax error, unexpected tSTRING_BEG, expecting keyword_end
...:shell, path: "vm-bootstrap.sh",privileged: false, args: [ "...

**Comment by mziwisky** [comment]
what versions of ruby and vagrant are you using?
